### ISSUE TITLE
Invalid domains (illegal characters)

### ISSUE THREAD

**Issue by p1r473** [hemiipatu/Blocklists#1]
I did not check all of your lists, but I checked a few, and found many illegal domains.

advertisement.txt:
```
särahah.eu
särahah.pl
```
phishing.txt:
```
bireysel-zîraat.com
www.hualañe.cl
bireysel-z?raat.com
www.huala?e.cl
```

**Comment by hemiipatu** [comment]
All known instances of illegal domains have been removed.
