### ISSUE TITLE
Is this list actively maintained?

### ISSUE THREAD

**Issue by p1r473** [hemiipatu/Blocklists#17]
@hemiipatu

**Comment by hemiipatu** [comment]
Hey @p1r473 apologies for the tremendously late replies to your comments! 

I can see that you've been busy and have found numerous issues with the lists. As it stands the lists aren't upto-date but I will take the time to get them updated and review then implement the changes as per your suggestions.

I hope to do this by 26/11/2020 during my rest period from work.

**Comment by p1r473** [comment]
Thanks!
